Expense01/Controllers/CatagoriesController.cs
using Expense01.Data;
using Expense01.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Expense01.Controllers
{
    [Authorize]
    public class CatagoriesController : Controller
    {
        private readonly ApplicationDbContext db;

        public CatagoriesController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            ViewBag.Count = db.dailyExpense.Count();

            var Total = db.dailyExpense.Select(x => x.Amount).Sum();
            ViewBag.Amount = Total.ToString("0.00");

            var maxx = db.dailyExpense.Max(x => x.Amount);
            ViewBag.M = maxx;

            var avg = db.dailyExpense.Average(x=>x.Amount);
            ViewBag.a = avg;

            var q = db.dailyExpense.Select(w=>w.EName);
            var m = q.Max();
            ViewBag.l = m;

            return View(db.categories.ToList());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categories c)
        {
            if (ModelState.IsValid)
            {
                if(db.categories.Any(x=>x.CName.ToLower() == c.CName.ToLower()))
                {
                    ModelState.AddModelError("", "Category name already exits");
                    return View(c);
                }
                db.categories.Add(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);
        }

        public async Task<IActionResult> Edit(int id)
        {
            return View(db.categories.FirstOrDefault(x=>x.CategoriesId == id));
        }

        [HttpPost]
        public IActionResult Edit(Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categories).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var n = db.categories.FirstOrDefault(x=>x.CategoriesId == id);
            if (n == null)
            {
                return NotFound();
            }
            return View(n);
        }

        [HttpPost]
        public IActionResult Delete(Categories categories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categories).State = Microsoft.EntityFrameworkCore.EntityState.Deleted;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categories);
        }
    }
}

Expense01/Controllers/UserController.cs
using Expense01.Data;
using Expense01.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Expense01.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext Db;

        public UserController (UserManager<IdentityUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            this.Db = db;
        }
        public IActionResult Index()
        {
            return View(Db.Appusers.ToList());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AppUser appusers)
        {
            if (ModelState.IsValid)
            {
                var res = await _userManager.CreateAsync(appusers, appusers.PasswordHash);
                if (res.Succeeded)
                {
                    TempData["Save"] = "Data Save Successfully";
                    return RedirectToAction("Index");
                }
                foreach (var error in res.Errors)
                {
                    ModelState.AddModelError(String.Empty, error.Description);
                }
            }
            return View();  
        }

        public async Task<IActionResult> Edit(String id)
        {
            var u = Db.Appusers.FirstOrDefault(x=>x.Id == id);
            if(u == null)
            {
                return NotFound();
            }
            return View(u);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AppUser appUser)
        {
            var userinfo = Db.Appusers.FirstOrDefault(x=>x.Id == appUser.Id);
            if (userinfo == null)
            {
                return NotFound();
            }
            userinfo.FirstName = appUser.FirstName;
            userinfo.LastName = appUser.LastName;
            userinfo.UserName = appUser.UserName;
            userinfo.Email = appUser.Email;
            userinfo.PasswordHash = appUser.PasswordHash;

            var q = await _userManager.UpdateAsync(userinfo);
            if (q.Succeeded)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Info(String id)
        {
            var u = Db.Appusers.FirstOrDefault(x => x.Id == id);
            if (u == null)
            {
                return NotFound();
            }
            return View(u);
        }

        public async Task<IActionResult> Lock(String id)
        {
            var u = Db.Appusers.FirstOrDefault(x => x.Id == id);
            if (u == null)
            {
                return NotFound();
            }
            return View(u);
        }
        [HttpPost]
        public async Task<IActionResult> Lock(AppUser app)
        {
            var u = Db.Appusers.FirstOrDefault(x=>x.Id == app.Id);
            if (u == null)
            {
                return NotFound();
            }

            u.LockoutEnd = DateTime.Now.AddDays(99);
            int r = Db.SaveChanges();

            if (r > 0)
            {
                return RedirectToAction("Index");
            }
            return View(u);
        }

        public async Task<IActionResult> Act(String id)
        {
            var u = Db.Appusers.FirstOrDefault(x => x.Id == id);
            if (u == null)
            {
                return NotFound();
            }
            return View(u);
        }
        [HttpPost]
        public async Task<IActionResult> Act(AppUser app)
        {
            var u = Db.Appusers.FirstOrDefault(x => x.Id == app.Id);
            if (u == null)
            {
                return NotFound();
            }

            u.LockoutEnd = null;
            int r = Db.SaveChanges();

            if (r > 0)
            {
                return RedirectToAction("Index");
            }
            return View(u);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var d = Db.Appusers.FirstOrDefault(x=>x.Id == id);
            if (d == null)
            {
                return NotFound();
            }
            return View(d);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(AppUser app)
        {
            var delU = Db.Appusers.FirstOrDefault(x=>x.Id == app.Id);
            if (delU == null)
            {
                return NotFound();
            }

            Db.Appusers.Remove(delU);
            int q = Db.SaveChanges();

            if (q > 0)
            {
                return RedirectToAction("Index");
            }

            return View(delU);
        }
    } 
}

Expense01/Views/Catagories/Create.cshtml
@model Expense01.Models.Categories

@{
    ViewData["Title"] = "Create";
}

<h2 class="text-success">Create New Category</h2>
<div class="col-12">
    <div class="d-flex justify-content-end mb-1">
        @*<a asp-controller="User" asp-action="Create" class="btn btn-outline-success">Add New</a>*@
    </div>
    <form asp-controller="CatagoriesController" asp-action="index"> </form>
</div>
<form asp-action="Create" method="post" enctype="multipart/form-data" class="text-light lead">
    <div class="p-4 rounded border">
        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <h3>@ViewBag.message</h3>

        <div class="form-group row">
            <div class="col-2">
                <label asp-for="CName"></label>
            </div>
            <div class="col-10">
                <input asp-for="CName" class="form-group" />
            </div>
            <span asp-validation-for="CName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-outline-primary" value="Save" />
            <a asp-action="Index" class="btn btn-outline-secondary">Back To Index</a>
        </div>

    </div>

</form>

Expense01/Views/Catagories/Delete.cshtml
@model Expense01.Models.Categories
@{
    ViewData["Titel"] = "Delete";
}

<h2 class="text-success">Delete Categories</h2>
<form asp-action="Delete" method="post" enctype="multipart/form-data" class="text-light lead">
    <input type="hidden" asp-for="CategoriesId" />
    <div class="p-4 rounded border">

        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <h3>@ViewBag.message</h3>

        <div class="form-group row">
            <div class="col-2">
                <label asp-for="CName"></label>
            </div>
            <div class="col-10">
                <input asp-for="CName" class="form-group" />
            </div>
            <span asp-validation-for="CName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-outline-primary" value="Delete" />
            <a asp-action="Index" class="btn btn-outline-secondary">Back To Index</a>

        </div>
    </div>
</form>

Expense01/Views/Catagories/Edit.cshtml
@model Expense01.Models.Categories
@{
    ViewData["Titel"] = "Edit";
}

<h2 class="text-success">Edit Categories</h2>
<form asp-action="Edit" method="post" enctype="multipart/form-data" class="text-light lead">
    <input type="hidden" asp-for="CategoriesId" />
    <div class="p-4 rounded border">

        <div asp-validation-summary="ModelOnly" class="text-danger">

        </div>
        <h3>@ViewBag.message</h3>

        <div class="form-group row">
            <div class="col-2">
                <label asp-for="CName"></label>
            </div>
            <div class="col-10">
                <input asp-for="CName" class="form-group" />
            </div>
            <span asp-validation-for="CName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-outline-primary" value="Save" />
            <a asp-action="Index" class="btn btn-outline-secondary">Back To Index</a>
     
        </div>
    </div>
</form>

@*<form asp-action="Edit" asp-controller="Catagories" method="post">
    <input type="hidden" asp-for="CategoriesId" />
    <div class="form-group row my-1">
        <label class="col-form-label col-form-label-sm col-2">Category Name</label>
        <div class="col-6">
            <input type="text" class="form-control form-control-sm" asp-for="CName" />
            <span asp-validation-for="CName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row my-1">

        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </div>
</form>
<a asp-action="Index" class="btn-link">Back to list</a>*@

@section scripts {
    <script src="~/libs/jquery/jquery.min.js"></script>
    <script src="~/libs/validation/jquery.validate.min.js"></script>
    <script src="~/libs/validation/jquery.validate.unobtrusive.min.js"></script>
}

Expense01/Views/Catagories/Index.cshtml
@model IEnumerable<Categories>

@{ 
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="card border-danger mt-4 bg-dark ml-3 col-3" style="max-width: 17rem;">
        <div class="card-body">
            <h5 class="card-title text-center">Total Expense</h5>
            <h1 class="text-center">@ViewBag.Count</h1>
        </div>
    </div>
    <div class="card border-danger col-3 mt-4 bg-dark ml-2" style="max-width: 17rem;">
        <div class="card-body">
            <h5 class="card-title text-center">Total Amount</h5>
            <h1 class="text-center">@ViewBag.Amount</h1>
        </div>
    </div>
    <div class="card border-danger col-3 mt-4 bg-dark ml-2" style="max-width: 17rem;">
        <div class="card-body">
            <h5 class="card-title text-center">Max Amount</h5>
            <h1 class="text-center">@ViewBag.M.ToString("0.00")</h1>
        </div>
    </div>
    <div class="card border-danger col-3 mt-4 bg-dark ml-2" style="max-width: 17rem;">
        <div class="card-body">
            <h5 class="card-title text-center">Max Expense</h5>
            <h1 class="text-center">@ViewBag.l</h1>
        </div>
    </div>
    <div class="col-12">
        <h2 class="text-success">Expnese Categories</h2>
        <div class="d-flex justify-content-end mb-1">
            <a asp-controller="Catagories" asp-action="Create" class="btn btn-primary btn-sm">Add New</a>
        </div>
    </div>
    <div class="col-12">
        <table class="table table-bordered text-white table-active text-center">
            <thead class="table-primary bg-light ">
                <tr>
                    <th>Category Name</th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var data in Model)
                {
                    <tr>
                        <td>@data.CName</td>
                        <td>
                            <a class="btn btn-primary btn-sm" asp-controller="Catagories" asp-action="Edit" asp-route-id="@data.CategoriesId">Edit</a>
                            <a class="btn btn-danger btn-sm" asp-controller="Catagories" asp-action="Delete" asp-route-id="@data.CategoriesId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>